#!/bin/sh

/usr/bin/invoke_app "$@" -C @tool/bin/BacMacroCC3D4.sh -t bacmacrocc3d4 \
                         -u compucell3d-4.2.2 \
                         -w captive \
                         -r none
